[package]
name = "jig-20-interface-http"
version = "0.1.0"
authors = ["Sean Cross <sean@xobs.io>"]

[dependencies]
iron = "0.5.1"
staticfile = "0.4.0"
mount = "0.3.0"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"
